# Generated by Django 5.0.2 on 2024-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='auto_store.category'),
        ),
    ]
