# Generated by Django 5.0.2 on 2024-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_store', '0003_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
